#!/bin/sh

set -eu

ANUSH_SYSTEM_DIR="${ANUSH_SYSTEM_DIR:-/usr/share/anush}"
export ANUSH_ROOT="${ANUSH_ROOT:-${XDG_CONFIG_HOME:-$HOME/.config}/anush}"
export ANUSH_CONFIG_DIR="${ANUSH_ROOT}/config"

if [ ! -d "$ANUSH_ROOT" ]; then
    mkdir -p "$(dirname "$ANUSH_ROOT")"
    cp -a "$ANUSH_SYSTEM_DIR" "$ANUSH_ROOT"
fi
